parameters:
  mailer_from_mail: '%env(MAILER_FROM_MAIL)%'
  mailer_from_name: '%env(MAILER_FROM_NAME)%'

swiftmailer:
    url: '%env(MAILER_URL)%'
    #spool: { type: 'memory' } # no need since we send mails through the queue workers
