language: bash
env:
  global:
    - PRIVATE_KEY=id_rsa_travis
#php:
#  - 7.1.9
addons:
  ssh_known_hosts: 178.172.173.6
before_install:
  - echo "before install"
install:
  - echo "install"
before_script:
  - echo "before script"
script:
  - echo "script"
before_deploy:
- openssl aes-256-cbc -K $encrypted_95927b30ba93_key -iv $encrypted_95927b30ba93_iv -in id_rsa_travis.enc -out ${PRIVATE_KEY} -d
- eval "$(ssh-agent -s)"
- chmod 600 ${PRIVATE_KEY}
- ssh-add ${PRIVATE_KEY}
deploy:
  provider: script
  skip_cleanup: true
  script: ssh chapal@178.172.173.6 -i ${PRIVATE_KEY} -o "StrictHostKeyChecking no" 'bash -s' < deploy.sh
  #- ssh chapal@178.172.173.6 -i ${PRIVATE_KEY} -o "StrictHostKeyChecking no" 'bash -s' < deploy.sh
  on:
    branch: master
after_success:
 - echo "Wow!"