version: '3'

volumes:
  mysql-invoicer-data:

services:
  invoicer-apache:
    build: .docker/apache
    container_name: invoicer-apache
    ports:
      - 8000:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/sf4
    depends_on:
      - invoicer-php

  invoicer-mysql:
    build: .docker/mysql
    container_name: invoicer-mysql
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-invoicer-data:/var/lib/mysql
    ports:
      - 3308:3306
    env_file:
      - ./.docker/mysql/.env

  invoicer-php:
    build: .docker/php
    container_name: invoicer-php
    volumes:
      - .:/home/wwwroot/sf4
    environment:
      - maildev_host=sf4_maildev
    depends_on:
      - invoicer-maildev
      - invoicer-mysql

  invoicer-maildev:
    image: djfarrelly/maildev
    container_name: invoicer-maildev
    ports:
      - 8001:80