version: '3'

volumes:
  mysql-invoicer-data:

services:
  invoicer-apache:
    build: .docker/apache
    image: invoicer-apache
    container_name: invoicer-apache
    ports:
      - 8000:80
    volumes:
      - .docker/apache/vhosts:/etc/apache2/sites-enabled
      - .:/home/www/invoicer
    depends_on:
      - invoicer-php

  invoicer-mysql:
    build: .docker/mysql
    image: invoicer-mysql
    container_name: invoicer-mysql
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-invoicer-data:/var/lib/mysql
    ports:
      - 3308:3306
    env_file:
      - ./.docker/mysql/.env

  invoicer-php:
    build: .docker/php
    image: invoicer-php
    container_name: invoicer-php
    volumes:
      - .:/home/www/invoicer:cached
    environment:
      - maildev_host=invoicer-maildev
    depends_on:
      - invoicer-maildev
      - invoicer-mysql

  invoicer-maildev:
    image: djfarrelly/maildev
    container_name: invoicer-maildev
    ports:
      - 1080:80

  invoicer-coverage:
    image: invoicer-php
    volumes:
      - .:/home/www/invoicer:cached
    command: >
      bash -c "./bin/phpunit --coverage-html tests/coverage
      && cd tests/coverage
      && php -S 0.0.0.0:8005"
    depends_on:
      - invoicer-php
    ports:
      - 8005:8005

  invoicer-rabbitmq:
    image: rabbitmq:3-management
    container_name: invoicer-rabbitmq
    ports:
      - 8080:15672